/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class homePage extends javax.swing.JFrame {
public String email;
    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
    }
       public homePage( String userEmail) {
        initComponents();
        email = userEmail;
        if (!email.equals("admin@gmail.com") ){
            btnmanagecategory.setVisible(false);
            btnnewproduct.setVisible(false);
            btneditproduct.setVisible(false);
            btnverifyusers.setVisible(false);
        }
            
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogout = new javax.swing.JButton();
        btnplaceorder = new javax.swing.JButton();
        btnviewbill = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnmanagecategory = new javax.swing.JButton();
        btnnewproduct = new javax.swing.JButton();
        btneditproduct = new javax.swing.JButton();
        btnverifyusers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        btnplaceorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnplaceorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/place order.png"))); // NOI18N
        btnplaceorder.setText("Place order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaceorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        btnviewbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnviewbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View Bills & Order Placed Details.png"))); // NOI18N
        btnviewbill.setText("View bill and placed order details ");
        btnviewbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit small.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 90, 40));

        btnmanagecategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/category.png"))); // NOI18N
        btnmanagecategory.setText("Manage Category");
        btnmanagecategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagecategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanagecategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        btnnewproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnewproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new product.png"))); // NOI18N
        btnnewproduct.setText("New Product");
        btnnewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, -1, -1));

        btneditproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneditproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view edit delete product.png"))); // NOI18N
        btneditproduct.setText("View Edit and Delete Product");
        btneditproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditproductActionPerformed(evt);
            }
        });
        getContentPane().add(btneditproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, -1));

        btnverifyusers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnverifyusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/verify users.png"))); // NOI18N
        btnverifyusers.setText("Verify Users");
        btnverifyusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyusersActionPerformed(evt);
            }
        });
        getContentPane().add(btnverifyusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-background-image.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, 1820, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        // TODO add your handling code here:
        
        PlaceOrder Pd = new PlaceOrder();
        Pd.setVisible(true);
    }//GEN-LAST:event_btnplaceorderActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
         int  a = JOptionPane.showConfirmDialog(null, "Do You Want to Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do You really want to Log out", "select" ,JOptionPane.YES_NO_OPTION );
        if (a==0){
        dispose();
         Login lf= new Login();
        lf.setVisible(true);
               
                }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnmanagecategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagecategoryActionPerformed
        // TODO add your handling code here:
      
        manageCategory mc = new manageCategory();
        mc.setVisible(true);
    }//GEN-LAST:event_btnmanagecategoryActionPerformed

    private void btnnewproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproductActionPerformed
        // TODO add your handling code here:
        
        Newproduct np = new Newproduct();
        np.setVisible(true);
    }//GEN-LAST:event_btnnewproductActionPerformed

    private void btneditproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditproductActionPerformed
        // TODO add your handling code here:
          editProduct ep = new editProduct();
        ep.setVisible(true);
    }//GEN-LAST:event_btneditproductActionPerformed

    private void btnverifyusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyusersActionPerformed
        // TODO add your handling code here:
          verifyUsers vu = new verifyUsers();
        vu.setVisible(true);
    }//GEN-LAST:event_btnverifyusersActionPerformed

    private void btnviewbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbillActionPerformed
        // TODO add your handling code here:
        viewBill vb= new viewBill();
        vb.setVisible(true);
    }//GEN-LAST:event_btnviewbillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditproduct;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmanagecategory;
    private javax.swing.JButton btnnewproduct;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JButton btnverifyusers;
    private javax.swing.JButton btnviewbill;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

